- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs # Stories-RoleTime
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 #5 hrs
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  special:
  # Stories skills - start
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        Guns: 0.9
        EnergyGuns: 0.9
        Medical: 0.3
  # Stories skills - end
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
