- type: job
  id: SpacePrisonMedic
  name: job-name-space-prison-medic
  description: job-description-space-prison-medic
  playTimeTracker: JobSpacePrisonMedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # 5 hours
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 10800 # 3 hours
  startingGear: SpacePrisonMedicGear
  icon: "JobIconSpacePrisonMedic"
  supervisors: job-supervisors-hosp
  canBeAntag: false
  access:
  - Security
  - Brig
  - MaintSP
  - ServiceSP
  - ExternalSP
  - MedicalSP
  - PrisonerSP
  - ShuttleSP
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: WeaponrySkill
      
- type: startingGear
  id: SpacePrisonMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalSP
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesBootsJackSP
    id: SpacePrisonMedicPDA
    belt: ClothingBeltMedicalFilled
    ears: ClothingHeadsetPrison
  innerclothingskirt: ClothingUniformJumpskirtSP
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
