- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobHeadOfSpacePrison

- type: playTimeTracker
  id: JobSpacePrisonOfficer

- type: playTimeTracker
  id: JobSpacePrisonEngineer

- type: playTimeTracker
  id: JobSpacePrisonMedic

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobJediNt
