# FURRY CONFIG

# [config]
# presets = "Stories/furry"

[whitelist]
enabled = true
reason = "–§—Ä—Ä... UwU..."

[adminlogs]
enabled = false

[game]
hostname = "üìö Space Stories - Furry üê∂"
role_timers = false
desc = "ü•ù –§—Ä—Ä—Ä—Ä..."
map_pool = "StoriesDefaultMapPool"

[shuttle]
auto_call_time = 0

[rules]
time = 0.0

[queue]
enabled = false

[atmos]
monstermos_rip_tiles = false

[infolinks]
discord = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
bug_report = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
github = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
wiki = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
appeal = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
patreon = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[auth]
mode = 1

[procgen]
preload = false

[netres]
limit = 30
