# UNIVERSE CONFIG

# [config]
# presets = "Stories/universe"

[adminlogs]
server_name = "Space Stories - Universe ğŸ‘©â€ğŸš€"

[game]
hostname = "ğŸ“š Space Stories - Universe ğŸ‘©â€ğŸš€ [TTS]"
lobbyduration = 210
round_restart_time = 120
soft_max_players = 130
desc = """
                  ğŸ“• ğ—¦ğ—½ğ—®ğ—°ğ—² ğ—¦ğ˜ğ—¼ğ—¿ğ—¶ğ—²ğ˜€ - Ğ¡ĞµÑ€Ğ²ĞµÑ€, ĞºĞ¾Ñ‚Ğ¾Ñ€Ñ‹Ğ¹ Ñ†ĞµĞ½Ğ¸Ñ‚ Role Play, ÑĞ¾Ğ·Ğ´Ğ°Ğ²Ğ°Ğ¹ ÑĞ²Ğ¾Ğ¸ Ğ¸ÑÑ‚Ğ¾Ñ€Ğ¸Ğ¸ Ñƒ Ğ½Ğ°Ñ! ğŸ“˜
â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ âœ§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢
  ğŸŒ  â‹® Ğ¡ĞµÑ€Ğ²ĞµÑ€ ÑĞ¾ ÑÑ€ĞµĞ´Ğ½Ğ¸Ğ¼ ÑƒÑ€Ğ¾Ğ²Ğ½ĞµĞ¼ Ñ‚Ñ€ĞµĞ±Ğ¾Ğ²Ğ°Ğ½Ğ¸Ğ¹ Ğº Ñ€Ğ¾Ğ»ĞµĞ²Ğ¾Ğ¼Ñƒ Ğ¾Ñ‚Ñ‹Ğ³Ñ€Ñ‹ÑˆÑƒ.
  ğŸ” â‹® ĞšĞ¾ÑĞ¼Ğ¸Ñ‡ĞµÑĞºĞ°Ñ Ñ‚ÑÑ€ÑŒĞ¼Ğ° - Ğ¾Ñ‚Ğ´Ğ°Ğ»ĞµĞ½Ğ½Ñ‹Ğ¹ Ğ¾Ğ±ÑŠĞµĞºÑ‚ Ğ² ĞºĞ¾ÑĞ¼Ğ¾ÑĞµ, ÑĞ¾Ğ´ĞµÑ€Ğ¶Ğ°Ñ‰Ğ¸Ğ¹ Ğ¾Ğ¿Ğ°ÑĞ½Ñ‹Ñ… Ğ¿Ñ€ĞµÑÑ‚ÑƒĞ¿Ğ½Ğ¸ĞºĞ¾Ğ².
  ğŸŒ‘ â‹® Ğ¢ĞµĞ½ĞµĞ¼Ğ¾Ñ€Ñ„Ñ‹ - ĞºÑƒĞ»ÑŒÑ‚ Ñ‚ÑŒĞ¼Ñ‹, Ğ±Ğ¾ÑÑ‰Ğ¸Ğ¹ÑÑ ÑĞ²ĞµÑ‚Ğ°. ĞŸĞ¾Ğ´Ñ‡Ğ¸Ğ½Ğ¸Ñ‚Ğµ Ğ¾Ğ±Ğ¸Ñ‚Ğ°Ñ‚ĞµĞ»ĞµĞ¹ ÑÑ‚Ğ°Ğ½Ñ†Ğ¸Ğ¸ Ğ¸ Ğ¿Ñ€ĞµĞ²Ğ¾Ğ·Ğ½ĞµÑĞ¸Ñ‚ĞµÑÑŒ.
  âš”ï¸ â‹® Ğ¡Ñ‚Ñ€Ğ°Ğ¶ ĞºĞ»Ğ¸Ğ½ĞºĞ° - Ğ²Ğ¾Ğ¸Ğ½ ÑĞ²ĞµÑ‚Ğ°, ÑÑ€Ğ°Ğ¶Ğ°ÑÑ‰Ğ¸Ğ¹ÑÑ ÑĞ²ĞµÑ‚Ğ¾Ğ²Ñ‹Ğ¼ ĞºĞ»Ğ¸Ğ½ĞºĞ¾Ğ¼ Ğ¸ Ğ¾ÑĞ¾Ğ±Ñ‹Ğ¼Ğ¸ ÑĞ¿Ğ¾ÑĞ¾Ğ±Ğ½Ğ¾ÑÑ‚ÑĞ¼Ğ¸.
  ğŸ”¥ â‹® Ğ˜Ğ½ĞºĞ²Ğ¸Ğ·Ğ¸Ñ‚Ğ¾Ñ€ - Ğ²Ğ¾Ğ¸Ğ½ Ñ‚ÑŒĞ¼Ñ‹, Ñ†ĞµĞ»ÑŒ ĞºĞ¾Ñ‚Ğ¾Ñ€Ğ¾Ğ³Ğ¾ ÑƒĞ½Ğ¸Ñ‡Ñ‚Ğ¾Ğ¶Ğ¸Ñ‚ÑŒ ÑÑ‚Ñ€Ğ°Ğ¶Ğ° ĞºĞ»Ğ¸Ğ½ĞºĞ°.
  ğŸ”Š â‹® TTS - 130 ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ñ‹Ñ… Ğ³Ğ¾Ğ»Ğ¾ÑĞ¾Ğ² Ğ´Ğ»Ñ Ğ²Ğ°ÑˆĞ¸Ñ… Ğ¿ĞµÑ€ÑĞ¾Ğ½Ğ°Ğ¶ĞµĞ¹.
  ğŸŒ â‹® ĞŸĞ¾Ğ»Ğ·Ğ°Ğ½Ğ¸Ğµ - ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ğ°Ñ Ğ¼ĞµÑ…Ğ°Ğ½Ğ¸ĞºĞ° Ğ¿Ğ¾Ğ»Ğ·Ğ°Ğ½Ğ¸Ñ, Ğ¿Ğ¾Ğ·Ğ²Ğ¾Ğ»ÑÑÑ‰Ğ°Ñ Ğ²Ğ°Ğ¼ ÑƒĞ¿Ğ°ÑÑ‚ÑŒ Ğ¸ Ğ¿Ğ¾Ğ»Ğ·Ñ‚Ğ¸.
  ğŸœ â‹® ĞšĞ¸Ğ´Ğ°Ğ½Ñ‹ - Ñ€Ğ°ÑĞ° Ğ³ÑƒĞ¼Ğ°Ğ½Ğ¾Ğ¸Ğ´Ğ½Ñ‹Ñ… Ğ¼ÑƒÑ€Ğ°Ğ²ÑŒĞµĞ², Ğ¾Ğ±Ğ»Ğ°Ğ´Ğ°ÑÑ‰Ğ¸Ğµ Ğ¾ÑĞ¾Ğ±Ğ¾Ğ¹ ÑĞ²ÑĞ·ÑŒÑ.
  ğŸ‘” â‹® ĞÑ‚Ğ·Ñ‹Ğ²Ñ‡Ğ¸Ğ²Ğ°Ñ Ğ°Ğ´Ğ¼Ğ¸Ğ½Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ, ĞºĞ¾Ñ‚Ğ¾Ñ€Ğ°Ñ Ğ¿Ğ¾ĞºĞ°Ğ¶ĞµÑ‚, Ñ€Ğ°ÑÑĞºĞ°Ğ¶ĞµÑ‚ Ğ¸ Ğ¿Ğ¾Ğ¼Ğ¾Ğ¶ĞµÑ‚ Ğ’Ğ°Ğ¼ Ğ¾ÑĞ²Ğ¾Ğ¸Ñ‚ÑÑ.
â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ âœ§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢
                                            ğŸ“š ĞŸÑ€Ğ¸ÑĞ¾ĞµĞ´Ğ¸Ğ½ÑĞ¹Ñ‚ĞµÑÑŒ Ğº Ğ½Ğ°ÑˆĞµĞ¼Ñƒ Ğ´Ñ€ÑƒĞ¶Ğ½Ğ¾Ğ¼Ñƒ ÑĞ¾Ğ¾Ğ±Ñ‰ĞµÑÑ‚Ğ²Ñƒ ğŸ“š"""
map_pool = "StoriesDefaultMapPool"

[admin]
deadmin_on_join = true
server_ban_hwid_ban_default = false

[vote]
restart_enabled = true
preset_enabled = false
map_enabled = false
restart_not_allowed_when_admin_online = true

[shuttle]
emergency_dock_time = 120
emergency_transit_time_min = 30
emergency_transit_time_max = 60
auto_call_time = 0

[rules]
time = 180.0

[queue]
enabled = true

[atmos]
monstermos_rip_tiles = false

[biomass]
easy_mode = false

[ic]
flavor_text = true

[infolinks]
discord = "https://discord.gg/space-stories"
wiki = "https://spacestories.club"
appeal = "https://discord.gg/space-stories"
patreon = "https://boosty.to/spacestories14"

[server]
rules_file = "StoriesRuleset"

[auth]
# Ğ’ĞºĞ»ÑÑ‡ĞµĞ½Ğ° Ğ±ĞµĞ· Ğ³Ğ¾ÑÑ‚ĞµĞ¹. (0 Ğ´Ğ»Ñ Ğ³Ğ¾ÑÑ‚ĞµĞ¹. 2 Ğ´Ğ»Ñ Ğ²Ñ‹ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ñ)
mode = 1

[procgen]
preload = false

[gateway]
generator_enabled = false

[netres]
limit = 10

[viewport]
maximum_width = 26
