- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Stories-RoleTime
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  equipment:
    head: ClothingHeadHatTophat
    jumpsuit: ClothingUniformJumpsuitBartender
    outerClothing: ClothingOuterVest
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
