- type: job
  id: JediNt
  name: страж клинка
  description: Встань на защиту станции со своим крутым мечом и способностями!
  playTimeTracker: JobJediNt
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobIAA
      time: 36000 # 10 hours # ! Почему так чертовски много?
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 18000 # 5 hours
  startingGear: JediNtGear
  icon: "JobIconJediNt"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        Melee: 1.0
    - type: Force
    - type: ForceUser
      preset: Jedi

- type: startingGear
  id: JediNtGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJediNt
    back: ClothingBackpackJediNtFilled
    shoes: ClothingShoesBootsJackJediNt
    eyes: ClothingEyesGlassesSecurity
    pocket1: LightSaberJediNt
    outerClothing: ClothingOuterVestJediNt
    id: JediNtPDA
    ears: ClothingHeadsetJediNtAlt
    belt: ClothingBeltSecurityFilled
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckMantleJediNt
  # innerclothingskirt: ClothingUniformJumpskirtSP
  # satchel: ClothingBackpackSatchelSpacePrisonFilled
  # duffelbag: ClothingBackpackDuffelSpacePrisonFilled

- type: startingGear
  id: JediGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJedi
    # back: ClothingBackpackJediNtFilled
    shoes: ClothingShoesBootsJackJedi
    # eyes: ClothingEyesGlassesSunglasses
    pocket1: LightSaberJediNt
    outerClothing: ClothingOuterCoatJediFilled
    id: JediNtPDA
    ears: ClothingHeadsetJediNtAlt
    belt: ClothingBeltJediFilled
    # gloves: ClothingHandsGlovesCombat
    # neck: ClothingNeckMantleJediNt
  # innerclothingskirt: ClothingUniformJumpskirtSP
  # satchel: ClothingBackpackSatchelSpacePrisonFilled
  # duffelbag: ClothingBackpackDuffelSpacePrisonFilled
