- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 43200 #12 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 43200 #12 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 216000 # 60 hrs
    - !type:RoleTimeRequirement
      role: JobStationChiefMedicalOfficer
      time: 10800 #3 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
