- type: job
  id: PRISONEngineer
  name: инженер космической тюрьмы
  description: Обслуживайте тюрьму, ибо сбежавшие зеки придут за вами в первую очередь.
  playTimeTracker: JobSpacePrisonEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 # 5 hours
  startingGear: PRISONEngineerGear
  icon: "JobIconSpacePrisonEngineer"
  supervisors: начальник тюрьмы
  canBeAntag: true
  access:
  - Prisoner
  - Prison
  - PrisonEng
  - Maintenance
  - External
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]

- type: startingGear
  id: PRISONEngineerGear
  equipment:
    jumpsuit: PRISONClothingUniformJumpsuitEngi
    id: PRISONPDAEngineer
    ears: PRISONClothingHeadsetEngi
    belt: ClothingBeltUtilityEngineering
