# MAPPERS CONFIG

# [config]
# presets = "_Stories/mappers"

[whitelist]
enabled = true
reason = "Ğ¢Ñ€ĞµĞ±ÑƒĞµÑ‚ÑÑ Ñ€Ğ°Ğ·Ñ€ĞµÑˆĞµĞ½Ğ¸Ğµ Ğ½Ğ° Ğ¿Ğ¾Ğ´ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ğµ Ğº ÑÑ‚Ğ¾Ğ¼Ñƒ ÑĞµÑ€Ğ²ĞµÑ€Ñƒ."

[adminlogs]
enabled = false

[game]
hostname = "ğŸ“š Space Stories - Mappers ğŸ—º"
role_timers = false
desc = "âš™ï¸ Ğ­Ñ‚Ğ¾ ÑĞµÑ€Ğ²ĞµÑ€ ğ—¦ğ—½ğ—®ğ—°ğ—² ğ—¦ğ˜ğ—¼ğ—¿ğ—¶ğ—²ğ˜€ Ğ´Ğ»Ñ Ğ¼Ğ°Ğ¿Ğ¿ĞµÑ€Ğ¾Ğ²."
map_pool = "StoriesDefaultMapPool"

[shuttle]
auto_call_time = 0

[rules]
time = 0.0

[queue]
enabled = false

[atmos]
monstermos_rip_tiles = false

[infolinks]
discord = "https://discord.gg/space-stories"
bug_report = "https://discord.com/channels/1111698541841240164/1112726172112007208"
github = "https://github.com/Space-_Stories/space-station-14"
wiki = "https://spacestories.club"
appeal = "https://discord.gg/space-stories"
patreon = "https://boosty.to/spacestories14"

[auth]
# Ğ’ĞºĞ»ÑÑ‡ĞµĞ½Ğ° Ğ±ĞµĞ· Ğ³Ğ¾ÑÑ‚ĞµĞ¹. (0 Ğ´Ğ»Ñ Ğ³Ğ¾ÑÑ‚ĞµĞ¹. 2 Ğ´Ğ»Ñ Ğ²Ñ‹ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ñ)
mode = 1

[procgen]
preload = false

[netres]
limit = 30

[viewport]
maximum_width = 26
